// src/test_helpers.rs
#[cfg(test)]
pub mod helpers {
    use crate::models::{ColumnData, ColumnSet};

    pub fn construct_column_set() -> ColumnSet {
        ColumnSet {
            columns: vec![
                ("header".into(), ColumnData::Strings(sample_header())),
                ("names".into(), ColumnData::Strings(sample_names())),
                ("versions".into(), ColumnData::Strings(sample_versions())),
                (
                    "sources".into(),
                    ColumnData::OptionalStrings(sample_sources()),
                ),
                (
                    "checksums".into(),
                    ColumnData::OptionalStrings(sample_checksums()),
                ),
                (
                    "dependencies".into(),
                    ColumnData::StringLists(sample_deps()),
                ),
            ],
        }
    }

    pub fn sample_header() -> Vec<String> {
        vec![
            "# This file is automatically @generated by Cargo.".into(),
            "# It is not intended for manual editing.".into(),
            "version = 4".into(),
        ]
    }

    pub fn sample_names() -> Vec<String> {
        vec!["serde", "tokio", "anyhow", "clap"]
            .into_iter()
            .map(String::from)
            .collect()
    }

    pub fn sample_versions() -> Vec<String> {
        vec!["1.0.288", "1.49.0", "1.0.102", "4.5.60"]
            .into_iter()
            .map(String::from)
            .collect()
    }

    pub fn sample_sources() -> Vec<Option<String>> {
        let reg = Some("registry+https://github.com/rust-lang/crates.io-index".to_owned());
        vec![reg.clone(), reg.clone(), reg, None]
    }

    pub fn sample_checksums() -> Vec<Option<String>> {
        vec![
            Some("aabbccdd".to_owned()),
            Some("11223344".to_owned()),
            Some("deadbeef".to_owned()),
            None,
        ]
    }

    pub fn sample_deps() -> Vec<Vec<String>> {
        vec![
            vec!["serde_derive".to_owned()],
            vec!["mio".to_owned(), "bytes".to_owned()],
            vec![],
            vec!["clap_builder".to_owned(), "clap_derive".to_owned()],
        ]
    }
}
